### ISSUE TITLE
Explorer is not showing updated usernames and search is down.

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-explorer#195]
![image](https://user-images.githubusercontent.com/52256509/71208321-25e24c00-227f-11ea-897f-9d5c574ff1b0.png)

**Comment by diwakergupta** [comment]
@ryanarndtcm can you add more color here? Search works fine for me (both STX addresses and names), I don't see any indication that it's not showing recent registrations either. Exactly what's the buggy behavior you're observing?

**Comment by ryanarndtcm** [comment]
Just like in the screenshot, last username is 4 hours ago, and the screen above is returned when searching a Stacks Wallet address: https://explorer.blockstack.org/?search=SP1KZ5VA1XGQRAFNEPNSR18Y0VYKQXAFMDXGZBWGJ

This is on chrome

**Comment by diwakergupta** [comment]
@ryanarndtcm where are you getting that URL from? When I search that address in the search bar, it goes to https://explorer.blockstack.org/address/stacks/SP1KZ5VA1XGQRAFNEPNSR18Y0VYKQXAFMDXGZBWGJ, which renders fine for me.

I see latest name registered 2 hrs ago, not 4.

**Comment by ryanarndtcm** [comment]
the URL is the result of using the search bar to search the Stacks Address. That is the URL that is returned

Just refreshed it and now its fine again. 

The user said this in email and it was my exact experience as well (the bold part)

I'm trying to use the blockstack explorer to see the status of my account. However, searching for my key returns nothing. It looks like the website is broken. It should at least output an error if it's not working. https://explorer.blockstack.org/?search=SP1KZ5VA1XGQRAFNEPNSR18Y0VYKQXAFMDXGZBWGJ

**I've had this problem before, and then it worked. What is the issue? Why isn't a simple search not working?**

**Comment by larrysalibra** [comment]
@diwakergupta username lookup and search doesn't work for me either.

Steps to reproduce:

1. Navigate to https://explorer.blockstack.org/
2. Type `larry.id` in the search box at the top of the page
3. Press enter
4. Observe URL changes to https://explorer.blockstack.org/?search=larry.id
5. **Expected results**: show search results or info about the specific matching username.Page contents remains the same as the homepage. **Actual result**: Home page is still displayed.

I see this same behavior on Safari 13.0.4 (15608.4.9.1.3), Chrome 79.0.3945.88 (Official Build) (64-bit) and Firefox 71.0 (64-bit) all on macOS Catalina 10.15.2 (19C57).

I also see the same behavior on my iPhone (iOS 13.3 (17C54)).

In network tools, I'm seeing a missing javascript resource https://explorer.blockstack.org/_next/static/6xkSYjOwjmrkI4a-5I6Pf/pages/index.js

I came across this issue because it appears a different missing javascript resource is breaking other functionality on the site (filing a bug momentarily). 

Perhaps some files from the build aren't getting deployed to the cloudflare CDN endpoints or there's some sort of cache invalidation problem. I'm connecting to the Chicago (ORD) cloudflare edge and seeing a cache hit from their edge for the missing resource. 

See screenshots below:

<img width="1125" alt="Screen Shot 2019-12-26 at 10 52 48 PM" src="https://user-images.githubusercontent.com/597182/71480288-3d977280-2833-11ea-9afe-264f1b473d23.png">
<img width="1153" alt="Screen Shot 2019-12-26 at 10 50 01 PM" src="https://user-images.githubusercontent.com/597182/71480291-438d5380-2833-11ea-95e0-bb02811fdd73.png">
<img width="1067" alt="Screen Shot 2019-12-26 at 10 48 05 PM" src="https://user-images.githubusercontent.com/597182/71480294-4720da80-2833-11ea-8364-6f4b83846183.png">

<img width="561" alt="Screen Shot 2019-12-26 at 11 05 53 PM" src="https://user-images.githubusercontent.com/597182/71480526-8996e700-2834-11ea-9fb7-5ff3f75f06f5.png">

**Comment by diwakergupta** [comment]
@larrysalibra thanks, if you re-do the search does it work or fails persistently? Feels like a caching issue. Given the holidays, PBC folks probably won't be able to dig into this until after the holidays; meanwhile, if any community members want to take a crack, go for it!

**Comment by larrysalibra** [comment]
It failed persistently on all browsers when I filed that issue. I’m in a different location and hitting the HKG cloudflare edge and 1 of the pages works fine but another has 404 on the JavaScript asset. Yes, seems like caching to me.


I don’t see how community members are going to help with a PBC caching issue unless you want to share your infrastructure credentials with everyone! 😉🤣

I’m happy to help diagnose after the holidays.

**Comment by diwakergupta** [comment]
@zone117x could you take a look? We've had many caching issues, so I suspect there's some architecture / design pattern change needed, as opposed to a one-off fix. cc/ @hstove for ideas.

@larrysalibra clearing the caches isn't really a fix; I meant more in the sense of how the explorer gets built and perhaps changing how various artifacts are cached. But, point taken :)
